[project]
name = "c-ai-mod-bot"
version = "0.1.0"
description = "A reddit bot for moderating c-ai scams"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "praw",
    "python-dotenv",
]
